# Generated by Django 2.2.4 on 2019-09-11 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['id']},
        ),
    ]
